## Basic Configuration
baseurl = "https://gchiesa.github.io/" 

publishDir = 'docs'

builddrafts = false
canonifyurls = false
languageCode = "en-us"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "PeppeWith3p"
title = 'g-c.dev'

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "g-c-dev" # Comment out to disable Disqus.
#googleAnalytics = "G-BBLW1NP2ZG"
enableRobotsTXT = true

## Site Settings
[params]
author = "Giuseppe Chiesa"
intro = "I’m Peppe, an italian Cloud Architect living in Amsterdam."
description = "I love my **beautiful fiancee** and my cat **Newton**. I enjoy **jazz** music, italian cooking and be surrounded by **open-minded** people."
authorimage = "peppewith3p.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "g-c.dev - Peppe Chiesa"
keywords = "cloud,infra,software,architecture,devop,sre"

## Social Accounts
[params.social]
github = "gchiesa"
# instagram = "<username>"
linkedin = "gchiesa"
twitter = "peppewith3p"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
# email = "you@example.com"

## Extras
[params.extra]
copyright = "© 2022. Giuseppe Chiesa. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true
highlightjsstyle = "stackoverflow-light"
googleAnalyticsGTag = "G-BBLW1NP2ZG"
displayrssicon = true


## Main Menu
 [[menu.main]]
     name = "posts"
     weight = 100
     identifier = "posts"
     url = "/posts/"
# [[menu.main]]
#     name = "about"
#     identifier = "about"
#     weight = 200
#     url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"